<?php
declare(strict_types=1);
require __DIR__.'/../api/db.php';
$challengeId='admin-memo-chain';
$conn=db();
$message='';
if(($_GET['admin_api']??'')==='flag'){header('Content-Type:text/plain; charset=utf-8');echo get_flag($conn,$challengeId)??'EST{missing_flag}';exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['memo'])){$body=(string)$_POST['memo'];$review=null;if(stripos($body,'admin_api=flag')!==false){$review='관리관 브라우저가 비공개 API를 호출함: '.(get_flag($conn,$challengeId)??'EST{missing_flag}');}$stmt=$conn->prepare('INSERT INTO admin_memos (body, review_result) VALUES (?, ?)');$stmt->bind_param('ss',$body,$review);$stmt->execute();$message='메모가 검토 대기열에 등록되었습니다.';}
$memos=$conn->query('SELECT body, review_result, created_at FROM admin_memos ORDER BY id DESC LIMIT 5');
?>
<!doctype html><html lang='ko'><head><meta charset='UTF-8'/><meta name='viewport' content='width=device-width, initial-scale=1.0'/><title>관리관 메모 연쇄 | EST 전술보안 인트라넷</title><link rel='stylesheet' href='/styles.css?v=military-3'/></head><body><main class='challenge-page'><a class='back-link' href='/'>작전 과제 목록</a><section class='challenge-detail'><div class='section-heading'><span>관리관 메모 연쇄</span><small>검문소 / 고급</small></div><div class='challenge-body'><p class='eyebrow'>400 전과 / 고급 작전</p><h1>검열관 메모 체계 침투</h1><p>야전 메모 체계는 입력값을 검토 화면에 다시 표시합니다. 관리관 검토 흐름이 어떤 권한으로 동작하는지 확인하고 최종 인증 표식까지 연결하십시오.</p><?php if($message): ?><div class='hint-box visible success-box'><p><?php echo htmlspecialchars($message,ENT_QUOTES,'UTF-8'); ?></p></div><?php endif; ?><form class='tool-form' method='post'><label for='memo'>작전 메모 내용</label><textarea id='memo' name='memo' rows='5'></textarea><button class='primary-button' type='submit'>메모 등록</button></form><div class='terminal'><?php if($memos): while($row=$memos->fetch_assoc()): ?><div><strong><?php echo htmlspecialchars($row['created_at'],ENT_QUOTES,'UTF-8'); ?></strong><p><?php echo $row['body']; ?></p><?php if($row['review_result']): ?><code><?php echo htmlspecialchars($row['review_result'],ENT_QUOTES,'UTF-8'); ?></code><?php endif; ?></div><?php endwhile; endif; ?></div><!-- SOURCE HINT: Saved memo content is rendered again during review. Check whether it becomes markup. --><!-- SOURCE HINT: A review can request /challenges/admin-memo-chain.php?admin_api=flag and leave the result in the log. --><form class='submit-row' data-flag-form data-challenge-id='<?php echo $challengeId; ?>'><input name='flag' placeholder='EST{...}' autocomplete='off'/><button class='primary-button' type='submit'>보고</button></form></div></section></main><div class='toast' id='toast' role='status' aria-live='polite'></div><script src='/app.js?v=team-required-1'></script></body></html>
