<?php
declare(strict_types=1);
require __DIR__.'/../api/db.php';
$challengeId='blind-notice';
$q=$_GET['q']??'';
$searched=array_key_exists('q',$_GET);
$match=false;$error='';
if($searched){$conn=db();$sql='SELECT id FROM blind_notices WHERE is_public = 1 AND title LIKE '.chr(39).'%'.$q.'%'.chr(39).' LIMIT 1';try{$result=$conn->query($sql);$match=$result&&$result->num_rows>0;}catch(Throwable $e){$error='조회 실패.';}}
?>
<!doctype html><html lang='ko'><head><meta charset='UTF-8'/><meta name='viewport' content='width=device-width, initial-scale=1.0'/><title>비문 공지 검색소 | EST 전술보안 인트라넷</title><link rel='stylesheet' href='/styles.css?v=military-3'/></head><body><main class='challenge-page'><a class='back-link' href='/'>작전 과제 목록</a><section class='challenge-detail'><div class='section-heading'><span>비문 공지 검색소</span><small>공지 검색 / 중상급</small></div><div class='challenge-body'><p class='eyebrow'>340 전과 / 중상급 작전</p><h1>비문 공지 검색소</h1><p>검색어는 공개 공지 제목 조회문에 그대로 들어갑니다. 화면에는 결과 존재 여부만 표시되므로, 조건을 조금씩 바꾸며 비공개 메모의 인증 표식을 추적하십시오.</p><form class='tool-form' method='get'><label for='q'>검색 질의</label><div class='submit-row compact-row'><input id='q' name='q' value='<?php echo htmlspecialchars($q,ENT_QUOTES,'UTF-8'); ?>' autocomplete='off'/><button class='primary-button' type='submit'>조회</button></div></form><?php if($searched): ?><div class='hint-box visible <?php echo $match?'success-box':''; ?>'><strong>조회 결과</strong><p><?php echo $error?'조회 오류':($match?'조건에 맞는 공지가 존재합니다.':'조회된 공지가 없습니다.'); ?></p></div><?php endif; ?><!-- 소스 힌트: SQL은 title LIKE '%입력값%' 형태로 조립된다. 따옴표를 닫고 OR 조건을 붙이면 참/거짓 신호를 만들 수 있다. --><!-- 소스 힌트: 비공개 메모의 body 안에 FLAG가 있다. 한 번에 출력하지 말고 SUBSTR/LIKE로 앞 글자부터 맞춰라. 반복 요청이 많아지므로 작은 스크립트로 자동화하는 편이 현실적이다. --><form class='submit-row' data-flag-form data-challenge-id='<?php echo $challengeId; ?>'><input name='flag' placeholder='FLAG{...}' autocomplete='off'/><button class='primary-button' type='submit'>보고</button></form></div></section></main><div class='toast' id='toast' role='status' aria-live='polite'></div><script src='/app.js?v=team-required-1'></script></body></html>
