<?php
declare(strict_types=1);
require __DIR__.'/../api/db.php';
$challengeId='reflected-board';
$conn=db();
$flag=get_flag($conn,$challengeId)??'FLAG{missing_flag}';
$flagEncoded=base64_encode($flag);
?>
<!doctype html><html lang='ko'><head><meta charset='UTF-8'/><meta name='viewport' content='width=device-width, initial-scale=1.0'/><title>반사 게시판 검색 | EST 전술보안 인트라넷</title><link rel='stylesheet' href='/styles.css?v=military-3'/><style>.xss-result{min-height:56px}.flag-lock{margin-top:14px}</style></head><body><main class='challenge-page'><a class='back-link' href='/'>작전 과제 목록</a><section class='challenge-detail'><div class='section-heading'><span>반사 게시판 검색</span><small>DOM XSS / 중급 입문</small></div><div class='challenge-body'><p class='eyebrow'>225 전과 / 중급 입문</p><h1>게시판 검색 반사 취약점 검증</h1><p>사내 게시판 검색 콘솔은 입력한 검색어를 결과 영역에 다시 표시합니다. 입력값이 단순 텍스트인지 HTML로 해석되는지 확인하고 브라우저에서 경보 호출을 발생시키십시오.</p><form class='tool-form' onsubmit='return false;'><label for='searchInput'>검색 질의</label><div class='submit-row compact-row'><input id='searchInput' autocomplete='off' placeholder='검색어를 입력하십시오'/><button class='primary-button' id='searchBtn' type='button'>검색</button></div></form><pre class='terminal xss-result' id='resultsBox'>검색 대기 중...</pre><div class='hint-box visible flag-lock' id='flagPanel'><strong>FLAG 잠김</strong><p id='flagBody'>alert() 호출이 감지되면 인증 표식이 표시됩니다.</p><code id='flagValue' style='display:none'></code></div><!-- 소스 힌트: 검색 결과 렌더링에 innerHTML이 사용된다. 입력값이 HTML 태그로 해석되는지 먼저 확인하라. --><!-- 소스 힌트: innerHTML로 삽입된 script 태그는 보통 실행되지 않는다. 이미지 오류 이벤트처럼 자동 실행되는 속성을 노려라. --><form class='submit-row' data-flag-form data-challenge-id='<?php echo $challengeId; ?>'><input name='flag' placeholder='FLAG{...}' autocomplete='off'/><button class='primary-button' type='submit'>보고</button></form></div></section></main><div class='toast' id='toast' role='status' aria-live='polite'></div><script>window.__flagModule={reveal:function(){return atob('<?php echo $flagEncoded; ?>');}};(function(){'use strict';const input=document.getElementById('searchInput'),btn=document.getElementById('searchBtn'),box=document.getElementById('resultsBox'),panel=document.getElementById('flagPanel'),body=document.getElementById('flagBody'),flag=document.getElementById('flagValue');function render(){box.innerHTML='검색 결과: '+input.value}btn.addEventListener('click',render);input.addEventListener('keydown',e=>{if(e.key==='Enter')render()});let solved=false;window.alert=function(){if(solved)return;solved=true;panel.classList.add('success-box');panel.querySelector('strong').textContent='FLAG 확보';body.textContent='XSS 페이로드 실행이 확인되었습니다.';flag.textContent=window.__flagModule.reveal();flag.style.display='block';};})();</script><script src='/app.js?v=reset-cleanup-1'></script></body></html>
