<?php
declare(strict_types=1);
require __DIR__.'/../api/db.php';
$challengeId='upload-dispatch';
$uploadDir=__DIR__.'/../assets/dispatch_uploads';
$publicPath='/assets/dispatch_uploads';
$message='';$uploadedUrl='';
if(!is_dir($uploadDir)){mkdir($uploadDir,0755,true);}
$flagFile=__DIR__.'/../assets/dispatch_uploads/.dispatch_flag';
if(!is_file($flagFile)){$conn=db();$flag=get_flag($conn,$challengeId)??'EST{missing_flag}';file_put_contents($flagFile,$flag.PHP_EOL);}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_FILES['dispatch_file'])){$file=$_FILES['dispatch_file'];$originalName=basename((string)$file['name']);$lowerName=strtolower($originalName);if($file['error']!==UPLOAD_ERR_OK){$message='업로드 실패.';}elseif(strpos($lowerName,'.png')===false&&strpos($lowerName,'.jpg')===false&&strpos($lowerName,'.jpeg')===false){$message='전송소는 파일명에 .png, .jpg, .jpeg가 포함된 첨부만 접수합니다.';}else{$safeName=preg_replace('/[^A-Za-z0-9._-]/','_',$originalName);$targetPath=$uploadDir.'/'.$safeName;if(move_uploaded_file($file['tmp_name'],$targetPath)){$uploadedUrl=$publicPath.'/'.rawurlencode($safeName);$message='검토 대기 첨부로 저장되었습니다.';}else{$message='첨부 파일을 저장하지 못했습니다.';}}}
?>
<!doctype html><html lang='ko'><head><meta charset='UTF-8'/><meta name='viewport' content='width=device-width, initial-scale=1.0'/><title>전송 파일 업로드 | EST 전술보안 인트라넷</title><link rel='stylesheet' href='/styles.css?v=military-3'/></head><body><main class='challenge-page'><a class='back-link' href='/'>작전 과제 목록</a><section class='challenge-detail'><div class='section-heading'><span>전송 파일 업로드</span><small>파일 업로드 / 고급</small></div><div class='challenge-body'><p class='eyebrow'>450 전과 / 고급 작전</p><h1>실행 가능한 첨부 은닉</h1><p>전송 포털은 작전 증빙 이미지를 접수해 공개 경로에 저장합니다. 파일명 검사가 허술하므로 웹 서버가 실행할 수 있는 첨부를 올려 숨겨진 전송 표식을 읽어내십시오.</p><form class='tool-form' method='post' enctype='multipart/form-data'><label for='dispatch-file'>증빙 이미지</label><input id='dispatch-file' name='dispatch_file' type='file'/><button class='primary-button' type='submit'>업로드</button></form><?php if($message): ?><div class='hint-box visible <?php echo $uploadedUrl?'success-box':''; ?>'><p><?php echo htmlspecialchars($message,ENT_QUOTES,'UTF-8'); ?></p><?php if($uploadedUrl): ?><p>저장 경로: <a href='<?php echo htmlspecialchars($uploadedUrl,ENT_QUOTES,'UTF-8'); ?>'><?php echo htmlspecialchars($uploadedUrl,ENT_QUOTES,'UTF-8'); ?></a></p><?php endif; ?></div><?php endif; ?><!-- 소스 힌트: 파일명 검사는 이미지 확장자 문자열 포함 여부만 본다. 마지막 확장자는 여전히 중요하다. --><!-- 소스 힌트: 업로드한 파일 기준 ../assets/dispatch_uploads/.dispatch_flag 를 읽어라. --><form class='submit-row' data-flag-form data-challenge-id='<?php echo $challengeId; ?>'><input name='flag' placeholder='EST{...}' autocomplete='off'/><button class='primary-button' type='submit'>보고</button></form></div></section></main><div class='toast' id='toast' role='status' aria-live='polite'></div><script src='/app.js?v=team-required-1'></script></body></html>
